spring.application.name=marketplace

management.endpoint.health.show-details=always
spring.docker.compose.lifecycle-management=start-only

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registration (Postgres 5435)
registration.datasource.url=jdbc:postgresql://localhost:5435/registration
registration.datasource.username=app
registration.datasource.password=app
registration.datasource.driver-class-name=org.postgresql.Driver
registration.jpa.properties.hibernate.hbm2ddl.auto=update

# Catalog (Postgres 5436)
catalog.datasource.url=jdbc:postgresql://localhost:5436/catalog
catalog.datasource.username=app
catalog.datasource.password=app
catalog.datasource.driver-class-name=org.postgresql.Driver
catalog.jpa.properties.hibernate.hbm2ddl.auto=create
